theme: jekyll-theme-minimal
title: Sanjit K. Kaul's page
logo: images/skkaul_Mar4_2019.png
description: I am currently an associate professor at IIIT-Delhi. My students and I like to refer to our group as the Wireless Systems Lab. I am also associated with the Infosys Center for Artificial Intelligence at IIIT-Delhi.
